# === Stage 38: Добавь расширенный набор тестов для ошибок и пограничных случаев ===
# Project: HomeMaintenance
def test_edge_cases():
    assert HomeMaintenance().add_room("Кухня").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-10", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Спальня").add_task("Пыление", "Еженедельная").add_worker("Боб").schedule("2026-10-11", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гостиная").add_task("Уборка", "Ежемесячная").add_worker("Виктор").schedule("2026-10-12", "Ежемесячная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Ванная").add_task("Очистка", "Еженедельная").add_worker("Герда").schedule("2026-10-13", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Пatio").add_task("Уход", "Еженедельная").add_worker("Джордж").schedule("2026-10-14", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Кладовая").add_task("Инвентарь", "Ежемесячная").add_worker("Элеонора").schedule("2026-10-15", "Ежемесячная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Коридор").add_task("Уборка", "Еженедельная").add_worker("Фрэнк").schedule("2026-10-16", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Сараи").add_task("Покраска", "Ежемесячная").add_worker("Грета").schedule("2026-10-17", "Ежемесячная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Сарай2").add_task("Уборка", "Еженедельная").add_worker("Гарри").schedule("2026-10-18", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Сараи3").add_task("Покраска", "Ежемесячная").add_worker("Грета").schedule("2026-10-19", "Ежемесячная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Сараи4").add_task("Уборка", "Еженедельная").add_worker("Гарри").schedule("2026-10-20", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-21", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж2").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-22", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж3").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-23", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж4").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-24", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж5").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-25", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж6").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-26", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж7").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-27", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж8").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-28", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж9").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-29", "Еженедельная").run() == "Запланировано"
    assert HomeMaintenance().add_room("Гараж10").add_task("Мойка", "Еженедельная").add_worker("Алекс").schedule("2026-10-30", "Еженедельная").run() == "Запланировано"
